### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by vmoens**
Strong versioning of dependencies can mess up existing envs and cross deps 

cc @vikashplus

### CODE REVIEW

**Comment by mees** [comment]
Just had the same issue when installing the repo into an existing conda env which had a higher pytorch version, it was downgraded as a result of installing r3m.

**Comment by vikashplus** [comment]
@suraj-nair-1 -- Can we relax these dependencies? We might have to validate that the published checkpoints load, and the numbers can be reproduced.

**Comment by suraj-nair-1** [comment]
Yeah this should be fine, let me just verify that numbers still reproduce as expected then I'll merge this.

**Comment by suraj-nair-1** [comment]
Ok just tested and with the most up to date torch, torchvision, and cuda the models load and the "Verifying Correct Installation" numbers are similar, so going to merge.

**Pull request merged**
